window.TCVLegal.boot({
  prefix: window.TCVNumbers.PREFIX.ica,
  storageKey: 'chendawan_ica_draft_v1',
  sheetId: 'ica-sheet',
  filePrefix: 'ICA',
  noId: 'docNo',
  hintId: 'docNoHint',
  relatedId: 'relatedNo',
  relatedTypes: ['QUO', 'MSA'],
  workerEmptyHint:
    'No contractor selected. <a href="../workforce/">Register the contractor</a> first.',
  workerFilterFn: function (w) {
    return w.type !== 'employee';
  },
  fieldIds: [
    'serviceCode',
    'jobNo',
    'issueNo',
    'docNo',
    'relatedNo',
    'workerId',
    'clientId',
    'clientName',
    'clientReg',
    'clientAddr',
    'projName',
    'totalFee',
    'tasks',
    'milestones',
    'milestonePay',
    'deliveryDates',
    'acceptance',
    'effDate',
    'signDate',
  ],
});
