window.TCVLegal.boot({
  prefix: window.TCVNumbers.PREFIX.ica,
  storageKey: 'chendawan_ica_draft_v1',
  sheetId: 'ica-sheet',
  filePrefix: 'ICA',
  noId: 'docNo',
  hintId: 'docNoHint',
  relatedId: 'relatedNo',
  fieldIds: [
    'serviceCode',
    'jobNo',
    'issueNo',
    'docNo',
    'relatedNo',
    'clientName',
    'clientReg',
    'clientAddr',
    'projName',
    'totalFee',
    'tasks',
    'milestones',
    'milestonePay',
    'deliveryDates',
    'acceptance',
    'effDate',
    'signDate',
  ],
});
